### PR TITLE
Remove py38-devel in tox as ansible@devel dropped support for py38

### PR DESCRIPTION
**Pull request by zhan9san**

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Sorry, too soon. See https://endoflife.date/python

You cannot really do this before molecule main does it.

**Comment by zhan9san** [comment]
Thanks for your reminder.

> ERROR: Package 'ansible-core' requires a different Python: 3.8.13 not in '>=3.9'

Let me remove the `py38-devel` in `tox` only.

**Comment by zhan9san** [comment]
@ssbarnea 

I believe the CI would work now.

Do you have any concern?

**Review by ssbarnea — APPROVED** [review]
Sorry, too soon. See https://endoflife.date/python

You cannot really do this before molecule main does it.

**Pull request merged**
