### PR TITLE
Fix to support logging into a Windows Container

### PR DESCRIPTION
**Pull request by tmeckel**
This PR contains a small addition to `driver.py`to be able to login into a Windows Container.

Related to: https://github.com/ansible-collections/community.docker/pull/96

### CODE REVIEW

**Comment by tmeckel** [comment]
@ssbarnea as @chrisjsewell I'm wondering about the errors in the pipeline and ask, if the tests are just broken.

**Comment by ssbarnea** [comment]
I am sure somethings are broken on CI and I hope someone will attempt to fix them. I am unable to do it myself but I will help with review and release. It is not uncommon to have to fix 2-3 other issues before you make you patch mergeable on open-source projects. :p ... not ideal, but the sad reality.

**Comment by tmeckel** [comment]
@ssbarnea Issue is that I even can't run `tox` locally in the **master branch** with success. 

On issue that I spotted easily was the fact that the repo does not contain a `docs` folder so that the tox tests `testenv:docs` and `testenv:docs-livereload` fail. So I removed those test from `tox.ini` for testing.

**Comment by tmeckel** [comment]
@ssbarnea The `tox` tests pass on my machine (except the ones for python 3.7, 3.8, 3.9 because I don't have those versions installed) but the pipeline is failed with the following error:

image

So I suspect Ansible isn't correctly installed via pip in the CI pipeline.

**Comment by ssbarnea** [comment]
I will close it as until https://github.com/ansible-collections/community.docker/pull/96 is merged and released we cannot do anything about it.

**Pull request closed without merging**
