### PR TITLE
bump community.docker dependency to a released version

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by zhan9san** [comment]
@ssbarnea 
Do we need to remove `requirements.yml` in root folder, https://raw.githubusercontent.com/ansible-community/molecule-docker/main/requirements.yml?

I don't think it is used.

**Comment by ssbarnea** [comment]
No longer used AFAIK and it would be a good idea to remove it in the same PR.

**Comment by evgeni** [comment]
CI failures seem unrelated (`actions/cache` failing with `Input required and not supplied: key`)

**Comment by ssbarnea** [comment]
As you are removing the file that determined which collections were installed, you need to replace it with the source file that determines the collection versions. See https://github.com/ansible-community/molecule-docker/blob/main/.github/workflows/tox.yml#L79 -- that is why is failing as you remove the file. Just use the source one and it should work: [.](https://github.com/ansible-community/molecule-docker/blob/main/src/molecule_docker/driver.py)

**Comment by zhan9san** [comment]
Instead of the `driver.py`, how about using another config file, and read the config file in `driver.py`?

```python
required_collections = {
    "community.docker": "3.0.0-a2",
    "ansible.posix": "1.4.0"
}
```

**Comment by evgeni** [comment]
So the `requirements.yml` file is still used for fetching deps for making `ansible-lint` happy. Dropping it makes lint unhappy and I have not enough knowledge of the codebase to proceed.

**Comment by zhan9san** [comment]
@evgeni 

Sorry to make you confused. Let us go back to the beginning if you don't mind.

The duplicate definitions can avoid complex logics.

Update both definitions in [requirements.yml](https://github.com/ansible-community/molecule-docker/blob/main/requirements.yml) and [driver.py](https://github.com/ansible-community/molecule-docker/blob/main/src/molecule_docker/driver.py#L268) and keep other files as before.

I can help merge it once it's done.

**Comment by evgeni** [comment]
done!

**Comment by zhan9san** [comment]
@evgeni 

Great, thanks for your contribution.

**Pull request merged**
